config/routes.rb
InterviewTestApp::Application.routes.draw do
  # The default landing page is users#index.
  root :to => redirect('/users')

  resources :users do
    get :test_password
    put :authenticate     # The HTTP verb is 'put' so that the password being tested is not visible in the URL's query params
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :username, :presence => true, :uniqueness => true
  validates :password, :presence => true, :on => :create

  # Returns an array of symbols for this user's security roles, e.g. [:producer, :actor].
  # Returns an empty array if this user has no security roles.
  def security_roles
    [:producer, :director, :actor].find_all { |role| self.send role }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  
  def index
    @users = User.order(:username)
    respond_with(@users)
  end

  def edit
    @user = User.find(params[:id])
    respond_with(@user)
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'User was successfully updated.'
    end
    respond_with(@user, :location => users_url)
  end

  def test_password
    @user = User.find(params[:user_id])
    respond_with(@user)
  end

  def authenticate
    @user = User.find(params[:user_id])
    password = (params[:user] || {})[:password]

    respond_to do |format|
      if @user.authenticate(password)
        format.html { redirect_to users_url, :notice => 'Password is authentic.' }
      else
        @user.errors.add :base, "Password is invalid"
        format.html { render :action => "test_password" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def table_boolean(val)
    val ? 'X' : (val.nil? ? ' ' : '-')
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InterviewTestApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="content">
<%- flash.each do |name, msg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
<%- end -%>
<%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.haml
= form_for @user do |f|
  -if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend Security Roles
    .field
      = f.label :producer
      = f.check_box :producer
    .field
      = f.label :director
      = f.check_box :director
    .field
      = f.label :actor
      = f.check_box :actor

  %fieldset
    %legend Change Password
    %p
      %em (leave empty to keep the current password)
    .field
      = f.label :password, "New password"
      = f.password_field :password
    .field
      = f.label :password_confirmation, "Confirm password"
      = f.password_field :password_confirmation

  .actions
    = f.submit 'Save'
    = link_to 'Cancel', users_path

app/views/users/edit.html.haml
%h1 User '#{@user.username}'

= render 'form'

app/views/users/index.html.haml
%h1 Users

%table
  %tr
    %th Username
    %th Producer
    %th Director
    %th Actor
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.username
      %td.boolean= table_boolean user.producer
      %td.boolean= table_boolean user.director
      %td.boolean= table_boolean user.actor
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Test Password', user_test_password_path(user)

app/views/users/test_password.html.haml
%h1 Test the Password for User '#{@user.username}'

= form_for @user, :url => user_authenticate_path(@user), :method => :put do |f|
  -if @user.errors.any?
    #error_explanation
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg


  %fieldset
    %legend Enter a Password
    .field
      = f.label :password
      = f.password_field :password

    .actions
      = f.submit 'Test Password'
      = link_to 'Cancel', users_path